# Different ADVERSARIAL ATTACKS
#python cool_mc.py --parent_run_id="54cfe828d1664d9890db735f2360ab6c" --project_name="taxi_experiments" --constant_definitions="MAX_JOBS=2,MAX_FUEL=10" --prism_dir="../prism_files" --prism_file_path="transporter.prism" --seed=128 --task="rl_model_checking" --prop="P=? [ F \"empty\" ]" --interpreter="temporal_adv_attacks;P=? [ (n_feature=1 & (X n_feature=1)) ];1;fgsm"
#python cool_mc.py --parent_run_id="54cfe828d1664d9890db735f2360ab6c" --project_name="taxi_experiments" --constant_definitions="MAX_JOBS=2,MAX_FUEL=10" --prism_dir="../prism_files" --prism_file_path="transporter.prism" --seed=128 --task="rl_model_checking" --prop="P=? [ F \"empty\" ]" --interpreter="temporal_adv_attacks;P=? [ (n_feature=1 & (X n_feature=1)) ];1;deepfool"

# Different Attack and Defenses
#python cool_mc.py --parent_run_id="54cfe828d1664d9890db735f2360ab6c" --project_name="taxi_experiments" --constant_definitions="MAX_JOBS=2,MAX_FUEL=10" --prism_dir="../prism_files" --prism_file_path="transporter.prism" --seed=128 --task="rl_model_checking" --prop="P=? [ F \"empty\" ]" --interpreter="temporal_adv_attack_and_defense;P=? [ F n_feature=1 ];1;fgsm;floor"
python cool_mc.py --parent_run_id="54cfe828d1664d9890db735f2360ab6c" --project_name="taxi_experiments" --constant_definitions="MAX_JOBS=2,MAX_FUEL=10" --prism_dir="../prism_files" --prism_file_path="transporter.prism" --seed=128 --task="rl_model_checking" --prop="P=? [ F \"empty\" ]" --interpreter="temporal_adv_attack_and_defense;P=? [ F n_feature=1  ];1;deepfool;round"
#python cool_mc.py --parent_run_id="54cfe828d1664d9890db735f2360ab6c" --project_name="taxi_experiments" --constant_definitions="MAX_JOBS=2,MAX_FUEL=10" --prism_dir="../prism_files" --prism_file_path="transporter.prism" --seed=128 --task="rl_model_checking" --prop="P=? [ F \"empty\" ]" --interpreter="temporal_adv_attack_and_defense;P=? [ (n_feature=1 & (X n_feature=1)) ];1;fgsm;floor"
#python cool_mc.py --parent_run_id="54cfe828d1664d9890db735f2360ab6c" --project_name="taxi_experiments" --constant_definitions="MAX_JOBS=2,MAX_FUEL=10" --prism_dir="../prism_files" --prism_file_path="transporter.prism" --seed=128 --task="rl_model_checking" --prop="P=? [ F \"empty\" ]" --interpreter="temporal_adv_attack_and_defense;P=? [ (n_feature=1 & (X n_feature=1)) ];1;deepfool;floor"
#python cool_mc.py --parent_run_id="54cfe828d1664d9890db735f2360ab6c" --project_name="taxi_experiments" --constant_definitions="MAX_JOBS=2,MAX_FUEL=10" --prism_dir="../prism_files" --prism_file_path="transporter.prism" --seed=128 --task="rl_model_checking" --prop="P=? [ F \"empty\" ]" --interpreter="temporal_adv_attack_and_defense;P=? [ F (n_feature=2 & (X n_feature=2)) ];1;fgsm;round"
#python cool_mc.py --parent_run_id="54cfe828d1664d9890db735f2360ab6c" --project_name="taxi_experiments" --constant_definitions="MAX_JOBS=2,MAX_FUEL=10" --prism_dir="../prism_files" --prism_file_path="transporter.prism" --seed=128 --task="rl_model_checking" --prop="P=? [ F \"empty\" ]" --interpreter="temporal_adv_attack_and_defense;P=? [ F (n_feature=2 & (X n_feature=2)) ];1;deepfool;round"

# Different Environments
# Cleaning Robot
#python cool_mc.py --prop="" --project_name="cleaning_system_experiments" --constant_definitions="" --prism_dir="../prism_files" --prism_file_path="cleaning_system.prism" --reward_flag=1 --seed=128 --layers=4 --neurons=512 --lr=0.0001 --batch_size=64 --num_episodes=27713 --eval_interval=100 --epsilon_dec=0.99999 --epsilon_min=0.1 --gamma=0.99 --epsilon=1 --replace=1024 --wrong_action_penalty=10000 --max_steps=100 --replay_buffer_size=300000 #--prop="Pmin=? [ F<=100 \"bad_event\" ]"
#python cool_mc.py --parent_run_id="a3fc7ab05b98476ca3f4c9a8ab592db9" --project_name="cleaning_system_experiments" --constant_definitions="" --prism_dir="../prism_files" --prism_file_path="cleaning_system.prism" --seed=128 --task="rl_model_checking" --prop="P=? [ F dirt1<0]" --interpreter="temporal_adv_attacks;P=? [ F (n_feature=0 & (X n_feature=1)) ];5;fgsm"
# Avoidance
#python cool_mc.py --task=safe_training --project_name="avoid_experiments" --rl_algorithm=dqn_agent --prism_file_path="avoid.prism" --constant_definitions="xMax=12,yMax=12,slickness=0.1" --prop=""  --reward_flag=1 --seed=128 --epsilon=0.5 --layers=2 --neurons=128 --epsilon_min=0.01  --num_episodes=3647 --eval_interval=100 --epsilon_dec=0.9999 --lr=0.001 --replay_buffer_size=200000 --training_threshold=10000
#python cool_mc.py --parent_run_id="738491a041614574b9d6a6501a915356" --project_name="avoid_experiments" --constant_definitions="xMax=4,yMax=4,slickness=0.1" --prism_dir="../prism_files" --seed=128 --prism_file_path="avoid.prism" --task="rl_model_checking" --prop="P=? [ F<=100 COLLISION=true ]" --interpreter="temporal_adv_attacks;P=? [ F (n_feature=0 & (X n_feature=1)) ];5;fgsm"